title: Paramita's Portfolio
email: ms.paramita.manna@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: ""
url: ""
github_username:  bitparamita
linkedin_username: "mparamita"

# Build settings
theme: minima
header_pages:
  - notice-period.markdown